# Generated by Django 4.2.2 on 2023-07-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contentn',
            new_name='content',
        ),
    ]
